### PR TITLE
Handle refresh parameter

### PR DESCRIPTION
**Pull request by Vaelatern**
I think this is the last thing. If you can run a test of this, I've run rudimentary tests myself, we can open a PR against salt itself tomorrow or the day after? I'm happy to PR unless you want to.

### CODE REVIEW

**Comment by yopito** [comment]
Sorry for late reply and thanks for this PR, that sounds good.
Before merging: should we invert the default for `refresh` parameter like this ?
```
 def upgrade(refresh=True):
```
It might be much usable, especially with repos that update frequently and do no keep older versions of packages (like `http://repo.voidlinux.eu`)

**Comment by Vaelatern** [comment]
Yes, inversion is a good idea.

**Comment by Vaelatern** [comment]
Mind if I PR this tomorrow?

**Comment by yopito** [comment]
merged with few minor fixes in comments.
@Vaelatern : please go ahead to request a PR to Salt, you're much more reactive and clever than me.
I suggest to fork upstream's saltstack repo, copy/paste/merges of your patches and files into it instead of rely on this branch.

**Pull request merged**
